algoritmo "semnome"
// Função :
// Autor :
// Data : 18/10/2024
// Seção de Declarações 
var
   numero: inteiro
inicio

      Escreval("Digite um numero: ")
      leia(numero)
      
      
      Se (numero >= 1) e (numero <= 30) Entao
      
         Escreval("O seu numero esta entre o intervalo de 1 a 30")
         
      Senao
         Escreval("O numero digitado nao esta dentro do intervalo de 1 a 30")
         
      FimSe
fimalgoritmo
