algoritmo "semnome"
// Função :
// Autor :
// Data : 25/10/2024
// Seção de Declarações 
var

         numero: inteiro
inicio

      //Para <variável contadora> de <vamor inicial> Ate <valor final> Faca
      
      //<instruções a serem executadas repetidamente até a <variável contadora > atingir o valor final


      //Fimpara
      
      Para numero de 1 ate 100 faca

           Escreval(numero)

      Fimpara

fimalgoritmo
