algoritmo "OU"
// Função :
// Autor :
// Data : 18/10/2024
// Seção de Declarações 
var
   marca: caracter
inicio


      Escreval("Digite uma marca de carro")
      leia(marca)
      
      Se (marca = "Toyota") ou (marca = "Fiat") Entao
      
         Escreval("A marca que foi citada é Toyota ou Fiat")
      
      Senao
      
           Escreval("Marca não é boa")
      
      FimSe
fimalgoritmo
