algoritmo "semnome"
// Função :
// Autor :
// Data : 21/10/2024
// Seção de Declarações 
var
numero : inteiro
inicio
      Escreval("Digite um numero inteiro")
      leia(numero)
      
      //mod 2 ele pega o resto de uma divisao por 2
      //se o resto for igual a 0 ele e par
      //se o resto nao for 0 ele e impar
      
      Se (numero mod 2 = 0) Entao


         Escreval("Esse numero e par")
         
      Senao


            Escreval("Esse numero e impar")
      Fimse
fimalgoritmo
