algoritmo "semnome"
// Função :
// Autor :
// Data : 26/10/2024
// Seção de Declarações 
var
nome: vetor [1..4] de caracter
indice: inteiro
inicio

      Para indice de 1 ate 4 Faca
      
           Escreval("Digite uma letra: ")
           leia(nome[indice])
      Fimpara
      
      
      Escreval("Letra posicao 1: ", nome[1])
      Escreval("Letra posicao 2: ", nome[2])
      Escreval("Letra posicao 3: ", nome[3])
      Escreval("Letra posicao 4: ", nome[4])
fimalgoritmo
