algoritmo "semnome"
// Função :
// Autor :
// Data : 25/10/2024
// Seção de Declarações 
var

   numeroPar, quantidadeVezes : inteiro
   
inicio

      numeroPar <- 2
      quantidadeVezes <-1
      
      Repita
      
            Escreval(numeroPar)
            numeroPar <- numeroPar + 2
            quantidadeVezes <- quantidadeVezes + 1
            
            
      Ate quantidadeVezes > 25
fimalgoritmo
