algoritmo "Exercicio 2"
// Função :
// Autor :
// Data : 16/10/2024
// Seção de Declarações 
var

   cliente : caractere
   minutos, totalApagar, equacao : real
   
inicio

      Escreval("Nome do cliente ")
      leia(cliente)
      
      Escreval("Quantos minutos o cliente ficou no computador?")
      leia(minutos)
      
      equacao <- (minutos / 60) * 2
      
      Escreval("O cliente deve pagar o valor de R$", equacao)

fimalgoritmo
