algoritmo "semnome"
// Função :
// Autor :
// Data : 22/10/2024
// Seção de Declarações 
var
   numero: inteiro
   soma: inteiro
inicio
      
      Enquanto numero <> 5 Faca
      
               Escreval("Digite um número")
               leia(numero)
               soma <- soma + numero
               
      FimEnquanto
      
      Escreval("Soma dos valores até o 5 =", soma)
      EScreval("Voce achou o numero 5")

fimalgoritmo
